spring.application.name=StudentManagementSpring

spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=postgres
spring.datasource.password=Rustam2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
